# Generated by Django 4.1.2 on 2023-03-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaPrecio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaprecio',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
