# Generated by Django 4.1.2 on 2023-03-14 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centroCostos', '0002_remove_centrocosto_nomempresa_and_more'),
        ('ingrediente', '0007_alter_ingrediente_estado'),
        ('receta', '0004_delete_recetadetalle'),
        ('listaPrecio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCentroCostos', models.CharField(max_length=100)),
                ('CentroCosto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroCostos.centrocosto')),
            ],
        ),
        migrations.CreateModel(
            name='Estandarizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEstandarizador', models.CharField(max_length=50, verbose_name='id Estandarizador')),
                ('porcionesEstandar', models.CharField(max_length=50, verbose_name='Porciones Estandar')),
                ('codCentroCostos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='centroCostos.centrocosto', verbose_name='Cod Centro Costos')),
                ('codIngrediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingrediente.ingrediente', verbose_name='Cod Ingrediente')),
                ('codListaPrecio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listaPrecio.listaprecio', verbose_name='Cod Lista Precio')),
                ('codReceta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receta.receta', verbose_name='Cod Receta')),
            ],
        ),
    ]
